### ISSUE TITLE
Code: Connect the Project to external Datasource using JDBC

### ISSUE THREAD

**Issue by sameer90** [sameer90/REMS#4]
While running the registration module the code is throwing the exception below:
22:09:28,991 ERROR [stderr](default task-11) javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement

22:09:28,991 ERROR [stderr](default task-11)   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)

22:09:28,991 ERROR [stderr](default task-11)   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)

22:09:28,991 ERROR [stderr](default task-11)   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)

22:09:28,991 ERROR [stderr](default task-11)   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187)

22:09:28,991 ERROR [stderr](default task-11)   at com.rems.model.UserModel.addUser(UserModel.java:81)

22:09:28,991 ERROR [stderr](default task-11)   at com.rems.servlets.RegisterUser.doPost(RegisterUser.java:72)

22:09:28,991 ERROR [stderr](default task-11)   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

22:09:28,991 ERROR [stderr](default task-11)   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

22:09:28,991 ERROR [stderr](default task-11)   at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)

22:09:28,991 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

22:09:29,006 ERROR [stderr](default task-11)   at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)

22:09:29,006 ERROR [stderr](default task-11)   at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)

22:09:29,006 ERROR [stderr](default task-11)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)

22:09:29,022 ERROR [stderr](default task-11)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)

22:09:29,022 ERROR [stderr](default task-11)   at java.lang.Thread.run(Thread.java:722)

22:09:29,022 ERROR [stderr](default task-11) Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:196)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:122)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.prepare(IdentityGenerator.java:89)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:55)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:492)

22:09:29,022 ERROR [stderr](default task-11)   at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:197)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:181)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:216)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:334)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:289)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:195)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:126)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)

22:09:29,038 ERROR [stderr](default task-11)   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)

22:09:29,038 ERROR [stderr](default task-11)   ... 31 more

22:09:29,038 ERROR [stderr](default task-11) Caused by: org.h2.jdbc.JdbcSQLException: Table "ROOM" not found; SQL statement:
22:09:29,038 ERROR [stderr](default task-11) insert into room (roomDescription) values (?) [42102-173]

22:09:29,038 ERROR [stderr](default task-11)   at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)

22:09:29,038 ERROR [stderr](default task-11)   at org.h2.message.DbException.get(DbException.java:171)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.message.DbException.get(DbException.java:148)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.readTableOrView(Parser.java:4864)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.readTableOrView(Parser.java:4842)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.parseInsert(Parser.java:974)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.parsePrepared(Parser.java:375)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.parse(Parser.java:279)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.parse(Parser.java:251)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.command.Parser.prepareCommand(Parser.java:218)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.engine.Session.prepareLocal(Session.java:428)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.engine.Session.prepareCommand(Session.java:377)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)

22:09:29,053 ERROR [stderr](default task-11)   at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1076)

22:09:29,053 ERROR [stderr](default task-11)   at org.jboss.jca.adapters.jdbc.WrappedConnection.prepareStatement(WrappedConnection.java:529)

22:09:29,053 ERROR [stderr](default task-11)   at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$2.doPrepare(StatementPreparerImpl.java:124)

22:09:29,053 ERROR [stderr](default task-11)   at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)

22:09:29,053 ERROR [stderr](default task-11)   ... 53 more

**Comment by sameer90** [comment]
Resolved
